### ISSUE TITLE
Unclear structure of the list file that is required for feature extraction

### ISSUE THREAD

**Issue by think-high** [facebookresearch/R2Plus1D#11]
The file structure for list file that is required for feature extraction is:
org_video,label,start_frm,video_id

I am confused about the video_id here. According to the [feature extraction tutorial](https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/feature_extraction.md) each clip has a different video_id, but according to the list files available on the dropbox [here](https://www.dropbox.com/s/fyz9fec72v7gbxj/list.tar.gz), all the clips from the same video should have the same video_id. I personally think that the latter should be correct. 

Can you help me here? Also, why do the files on that dropbox link has start_frm difference of 1 frame? That's like each frame is considered as a clip, right?

Thanks

**Comment by dutran** [comment]
That list is for different purpose, e.g. dense prediction where we don't really care about the identities of clips within a video, for example, we just want to average pool the predictions to make the video-level prediction. However, for some other use cases, e.g. detection, if we want to have the real identities of clip, then we can keep the video_id for each clip different so after feature extraction we can have a corresponding map between features and clips.

**Comment by think-high** [comment]
Oh, I see. Thanks for the help.

**Comment by think-high** [comment]
And what's the reason for the 1 frame clips though?
