### ISSUE TITLE
Kinetics preprocessing

### ISSUE THREAD

**Issue by AustinVan** [facebookresearch/R2Plus1D#14]
In the tutorial of training kinetics, we need to pre-process the video as clips(of 10second).   Since the number of video is huge and the total time of each video varies, it may take time to finish the preprocessing.         
can you provide your script for this?

**Comment by cr-hxfan** [comment]
I have a nother question,
For UCF101, do we need to pre-process(like using fmmpeg)  to make the video as clips(of 10 seconds)

**Comment by cr-hxfan** [comment]
In addition, 
in the UCF101 list, there are the only test and train lists.

But where is the validation list? is it incorporated into training list?

**Comment by murilovarges** [comment]
Hi @AustinVan and @cr-hxfan,

The caffe2 framework has tools to preprocess videos ([Caffe2 Video tools)](https://github.com/pytorch/pytorch/tree/master/caffe2/video). So you don't need split videos in clips (e.g. clips with 32 frames).

Basically, you need to create an LMDB dataset with raw videos to do temporal jittering [(Example LMBD with Raw Videos)](https://github.com/facebookresearch/R2Plus1D/blob/master/scripts/create_hmdb51_lmdb.sh) or and LMDB with videos and start frame to extract dense features after train the model [(Exemple LMDB for Feature Extraction)](https://github.com/facebookresearch/R2Plus1D/blob/master/scripts/create_hmdb51_lmdb_feature_extraction.sh).

**Comment by cr-hxfan** [comment]
@murilovarges Thanks for the reply.

**Comment by FesianXu** [comment]
@murilovarges Hi, murilo, sorry for bothering, but I want to know the pixel range of the videos, is range from 0 to 1 or from 0 to 255 ? do we need other specify pre-processing? thanks.
