### ISSUE TITLE
Error when finetune UCF101

### ISSUE THREAD

**Issue by murilovarges** [facebookresearch/R2Plus1D#2]
Hi,

I'm trying to finetune using the script "finetune_ucf101.sh" I follow the tutorial "https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/hmdb51_finetune.md".

Follow the errors:
Traceback (most recent call last):
  File "tools/train_net.py", line 501, in <module>
    main()
  File "tools/train_net.py", line 496, in main
    Train(args)
  File "tools/train_net.py", line 280, in Train
    net_type=('prof_dag' if args.profiling == 1 else 'dag'),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 31, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 207, in Parallelize
    input_builder_fun(model_helper_obj)
  File "tools/train_net.py", line 268, in add_video_input
    use_local_file=args.use_local_file,
  File "/home/murilo/R2Plus1D/lib/utils/model_helper.py", line 127, in AddVideoInput
    data, label = model.net.VideoInput(
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py", line 2054, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []

**Comment by dutran** [comment]
@murilovarges Did you compiled caffe2 with openCV and ffmpeg flags are ON. I think CMake could not detect your dependencies, thus compile w/o VideoInputOp.

**Comment by fengwuxuan** [comment]
I got a same error with opencv 3.4.1, @murilovarges  did you solve it?

**Comment by murilovarges** [comment]
Hello @dutran I compiled caffe2 with openCV 3.4.1 and ffmpeg flags are ON, but I still with same errors.

**Comment by dutran** [comment]
I assume you install caffe2 from this https://github.com/pytorch/pytorch and follow instructions from here: https://caffe2.ai/docs/getting-started.html?configuration=compile . Do you install caffe2 pre-build or from source, pre-build version may not include VideoInputOp.

**Comment by dutran** [comment]
try to compile caffe2 yourself, follow https://caffe2.ai/docs/getting-started.html?configuration=compile when you do ```cmake ..```, you should get a summary about dependencies found by cmake, make sure it found ffmpeg, OpenCV (check version).

**Comment by dutran** [comment]
I used the latest on compiled from source (https://trac.ffmpeg.org/wiki/CompilationGuide/Centos) tested on CentOS.

**Comment by dutran** [comment]
@murilovarges: @CHJoanna from our team has just double checked the wrote some installation note [installation guide](tutorials/Installation_guide.md) in case you need a reference.

**Comment by bjuncek** [comment]
@murilovarges is your openCV compiled with CUDA support? 
I ran into a similar issue (it was on centOS7 with OpenCV 2.4.x, and it got solved when I recompiled the OpenCV to 3.4.x with  
`-D WITH_CUDA=ON ` option on and then recompiled cafe again.

For complete transparency, I used following parameters when configuring OpenCV, and the instructions found [here](https://www.pyimagesearch.com/2016/07/11/compiling-opencv-with-cuda-support/):

```cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D WITH_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_CUBLAS=1 \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.1.0/modules \
    -D BUILD_EXAMPLES=ON \
    -D BUILD_SHARED_LIBS=ON ..
```

**Comment by dutran** [comment]
@murilovarges have you got your compiling issue solved?

**Comment by murilovarges** [comment]
Hi @dutran, thank you very much for the tutorial, I'm using Ubuntu 16.04 and facing some problems with OpenCV compilation. I'll work in this today and report the result here.

**Comment by murilovarges** [comment]
Thank you so much @dutran and @CHJoanna, I followed the tutorial with some minor changes for Ubuntu and now I'm able to run the script for "fine tuning" without "VideoInput" errors.

**Comment by dutran** [comment]
Great!

**Comment by MuchaoYe** [comment]
> Thank you so much @dutran and @CHJoanna, I followed the tutorial with some minor changes for Ubuntu and now I'm able to run the script for "fine tuning" without "VideoInput" errors.

Hi, currently I meet a problem the same as yours. Could you tell me how did you solve your problem?
