### ISSUE TITLE
What is the difference between clip1 accuracy and video accuracy?

### ISSUE THREAD

**Issue by wenjie710** [facebookresearch/R2Plus1D#23]
Table 4 in the paper shows the clip1 accuracy and video1 accuracy of different methods, but I am confused about the difference between this two accuracies. It seems that the video1 accuracy is higer than clip1 accuracy.

**Comment by murilovarges** [comment]
Hi @wenjie710,

A video is composed of many clips (e.g. each clip with 32 frames), so clip1 accuracy is the rate of correct classification per clip. While Video accuracy is the rate of correct classification of a video after doing dense prediction aggregation "[dense_prediction_aggregation.py](https://github.com/facebookresearch/R2Plus1D/blob/master/tools/dense_prediction_aggregation.py)" using all clips of a given video.

**Comment by dutran** [comment]
Thank @murilovarges for helping. As murilovarges mentioned, you can use dense prediction to compute the video-level accuracy. Alternatively, depend on you GPU memory, some small models or model trained on short-clips (8-frame or 16-frame clips), you can use test_net.py to test which can aggregate prediction from 10-clips per video.

**Comment by JinyangGuo** [comment]
Hi, 

For the clip level accuracy, what if the last clip is not long enough? For example, we can split the video into several 16-frame clips. But the last clip is shorter than 16 frame. How can we handle this clip?
