### ISSUE TITLE
What does this warning mean: "Failed to parse extra data." when extracting features

### ISSUE THREAD

**Issue by think-high** [facebookresearch/R2Plus1D#25]
When extracting features, I am getting this warning:

![feature extraction warning](https://user-images.githubusercontent.com/5360126/42699477-8105c026-8686-11e8-8e7b-f8e1ba0d54e1.png)

What does this warning mean?

**Comment by dutran** [comment]
You can just ignore those ffmpeg warnings.

**Comment by LLLLLLI** [comment]
I meet this warning too.
How can I disable them?
