### ISSUE TITLE
What happens when I pass a different crop size during feature extraction then the crop size used in the training?

### ISSUE THREAD

**Issue by think-high** [facebookresearch/R2Plus1D#29]
Hi,

I am using the pre-trained models provided in this repo, to extract features. I have a couple of questions regarding the crop-size argument:

1). If I let the crop-size be the default (i.e 112) then it crops the video to that size instead of resizing, right?
2). What If I don't want to crop the video because my video's dimension is way larger. Then what happens if I pass a different value to the crop-size during feature extraction?

TIA,
Rahul

**Comment by think-high** [comment]
Okay, I throws an error if I give a different crop size, which is what I expected. So, if I need to let it take the entire width and height then should I am guessing that I need to change the scale_h and scale_w to 112, right? Assuming that it resizes the image to scale_h x scale_w. 

Can you put some light on that? TIA

**Comment by dutran** [comment]
Currently it works with crop_size 112x112 and length clip is a multiplier of 8. If you like to do something like FCN, you need to modify the final global pooling kernel size.
