### ISSUE TITLE
Error executing sh scripts/extract_feature_hmdb51.sh, Cannot open file: r2plus1d_8.mdl

### ISSUE THREAD

**Issue by 953585130** [facebookresearch/R2Plus1D#48]
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 921
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:model_helper:Loading path: r2plus1d_8.mdl
Traceback (most recent call last):
  File "tools/extract_features.py", line 328, in <module>
    main()
  File "tools/extract_features.py", line 323, in main
    ExtractFeatures(args)
  File "tools/extract_features.py", line 142, in ExtractFeatures
    model_helper.LoadModel(args.load_model_path, args.db_type)
  File "/home/baihao/R2Plus1D-master/tools/utils/model_helper.py", line 90, in LoadModel
    meta_net_def = pred_exp.load_from_db(path, dbtype)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/predictor/predictor_exporter.py", line 211, in load_from_db
    assert workspace.RunOperatorOnce(create_db), (
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 165, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at db.cc:140] file_. Cannot open file: r2plus1d_8.mdl Error from operator: 
output: "!!PREDICTOR_DBREADER" name: "" type: "CreateDB" arg { name: "db_type" s: "minidb" } arg { name: "db" s: "r2plus1d_8.mdl" }

**Comment by 953585130** [comment]
@dutran 
I did not find the corresponding file in the pre-training model provided in Tutorial 5. The pre-training models provided are all pkl files, no mdl files. Is there no release of r2plus1d_8.mdl or is there a problem with my environment?

for ((i=1;i<=2;i++)); \
do \
python tools/extract_features.py \
--test_data=/data/users/trandu/datasets/hmdb51_feature_extraction/hmdb51_test_01_video_id_dense_l32_$i \
--model_name=r2plus1d --model_depth=34 --clip_length_rgb=32 \
--gpus=0,1,2,3,4,5,6,7 \
--batch_size=4 \
--load_model_path=r2plus1d_8.mdl --db_type=minidb \
--output_path=/data/users/trandu/datasets/hmdb51_features/ft/hmdb51_test_01_video_id_dense_l32_$i.pkl \
--features=softmax,label,video_id \
--sanity_check=1 --get_video_id=1 --use_local_file=1 --num_labels=51; \
done

**Comment by dutran** [comment]
I think the models are supposed to be downloaded from here: https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/models.md

**Comment by 953585130** [comment]
@dutran 
I have solved this problem. When I successfully fine-tune the hmde51 dataset, the r2plus1d_8.mdl file is automatically generated. This is the result: INFO:train_net:Test accuracy: 0.605

After the fine-tuning is over, I plan to follow the tutorial to achieve dense predictions. This problem occurs when I execute sh scripts/extract_feature_hmdb51.sh: 
[mpeg4 @ 0x7ebe90082d60] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter Without encoding but stream copy to fix it.
10260/20677 iterations
INFO:feature_extractor:10260/20677 iterations
[mpeg4 @ 0x7ebe94010dc0] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.

No error, it has been constantly appearing, will this have an impact on the results?

**Comment by dutran** [comment]
I expect very little impact on the results.
