### ISSUE TITLE
training on 2 GPUs

### ISSUE THREAD

**Issue by gurkirt** [facebookresearch/R2Plus1D#50]
I am training trying to train your model on 2 GPUs as shown in your script.
scripts/train_r2plus1d_kinetics.sh
Is it right that epoch size is 1M? Will I be able to reproduce your result in table 2 of paper using that script? I would just need to change the model type?

**Comment by gurkirt** [comment]
Another question about optimization step. Does parameter update by SGD is done every iteration or 64 training clips in case of 2 GPUs? Or is there any other of asynchronous implementation of SGD is being used?

**Comment by dutran** [comment]
1) yes (at the end of page 5: " Although Kinetics has only about 240k training videos, we set epoch size to be 1M for temporal jittering"). You supposed to get those numbers in table 2 using test_net.
2) yes.

**Comment by gurkirt** [comment]
Thank you very much for your reply. 
I am trying to reproduce your results from Table 2 in Pytorch. I am starting form R3D model. 
Base model type is resnet 18. 

Input transformations are the random crop to the entire input sequence, random horizontal flip, and normalisation with mean and std. Am I missing something? 

You mentioned temporal jittering, what is that?

Many thanks,
Gurkirt

**Comment by gurkirt** [comment]
Also, where are input transformations are specified in this code?

**Comment by gurkirt** [comment]
I am training the networks from scratch like you and see if I can reproduce your results using just 2 GPUs?

**Comment by dutran** [comment]
you should be able to do so. The transformations are implemented in VideoInputOp in caffe2 (pytorch).
