### ISSUE TITLE
Finetune using OpticalFlow Models

### ISSUE THREAD

**Issue by murilovarges** [facebookresearch/R2Plus1D#7]
Hi @dutran, 

First, thank you for making public this wonderful work.

I've already been able to use this code to finetune R(2+1)D model on my dataset and run dense prediction with success.

Now I would like to use Optical Flow for computing accuracy rate of R(2+1)D-Two-Stream and I have some questions:
1 - Can you provide the R(2+1)D-Flow trained in "Kinetics", because I found only trained "Sports1M+Kinetics"?
2 - Can you provide an example or tutorial that give more details of how to finetune Optical flow model, I notice that Optical flow models need a lot of parameters to train: frame_gap_of, sampling_rate_of, clip_length_of, flow_data_type, do_flow_aggregation, flow_alg_type?

Best regards,
Murilo Varges

**Comment by dutran** [comment]
@murilovarges 
1. https://www.dropbox.com/s/qd0wjvhtqt88qx4/r2.5d_d34_l32_from_scratch_of_bn0.9.pkl?dl=0

2. For the parameters of optical flows, you can check them here https://github.com/facebookresearch/R2Plus1D/blob/master/scripts/extract_feature_kinetics_of.sh

**Comment by swap2ag** [comment]
> @murilovarges
> 
> 1. https://www.dropbox.com/s/qd0wjvhtqt88qx4/r2.5d_d34_l32_from_scratch_of_bn0.9.pkl?dl=0
> 2. For the parameters of optical flows, you can check them here https://github.com/facebookresearch/R2Plus1D/blob/master/scripts/extract_feature_kinetics_of.sh

What does the file in 1 contains? Does it contain the weights of R(2+1)D model trained from scratch using kinetics flows?
