### ISSUE TITLE
Installation Guide for Ubuntu

### ISSUE THREAD

**Issue by starsdeep** [facebookresearch/R2Plus1D#8]
Hi, the installation guide is specifically for CentOS. Can you create an installation guide for Ubuntu?

**Comment by dutran** [comment]
@CHJoanna may be able to help.

**Comment by think-high** [comment]
Even I am using it on Ubuntu 16.04. So, I have created an equivalent installation guide for Ubuntu while I was installing it on my machine. Let me know if I can help.

**Comment by dutran** [comment]
@think-high feel free to send a PR. Thanks for your contribution.

**Comment by think-high** [comment]
@dutran : I haven't created a Pull Request earlier so it will take some time for me to read the guidelines and also figure out how it works. I am uploading the file here so that @starsdeep and others are not blocked. And then I will create a PR separately if still required. 
Let me know!

[Ubuntu Installation guide.docx](https://github.com/facebookresearch/R2Plus1D/files/2091663/Ubuntu.Installation.guide.docx)

**Comment by CHJoanna** [comment]
Add installation guide for Ubuntu 16.04, which is at the 2nd part of the [installation guide](https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/Installation_guide.md).

**Comment by nayyeraafaq** [comment]
CMakeFiles/Makefile2:1401: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Everything works untill caffe2 installation. But I am getting above error when try to install caffe2. My cmake summary is as below: Could anyone please help what's wrong with my installation ?? Thanks 

-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-9443-g9bf72b2-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
-- 
--   BUILD_CAFFE2          : ON
--   BUILD_ATEN            : OFF
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python executable   : /home/aafaq/yes/envs/pythorch1/bin/python
--     Pythonlibs version  : 2.7.13
--     Python library      : /home/aafaq/yes/envs/pythorch1/lib/python2.7
--     Python includes     : /home/aafaq/yes/envs/pythorch1/include/python2.7
--     Python site-packages: lib/python2.7/site-packages
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_ATEN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 9.2
--     cuDNN version       : 5.1.10
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
--     nvrtc               : /usr/lib/x86_64-linux-gnu/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : ON
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--     USE_GLOO_IBVERBS    : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
